# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 526737bf23c68ade017cc75afc61d6ac829886fd73085ad8b27962c72da155247da5ba5cae92a2324fc59d464ef20bbf6c594c85612ef21e84a4c77ebfa86735

test:
  secret_key_base: d4ee433bb2931acaf6da546ce6bae6d49d50398f1e1157cdc59c5f2f5ce4f3f7d9eb581b21cebd4c22ba18d60a64ac867e65e3c0ab875c170f626c8ccdc4dc50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
